export const actionConstants = {
    GETALL_REQUEST: 'GET_CLASSROOMS_REQUEST',
    GETALL_SUCCESS: 'GET_CLASSROOMS_SUCCESS',
    GETALL_FAILURE: 'GET_CLASSROOMS_FAILURE',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL'
};