export const classroomActions = {
    GETALL_REQUEST: 'GET_CLASSROOMS_REQUEST',
    GETALL_SUCCESS: 'GET_CLASSROOMS_SUCCESS',
    GETALL_FAILURE: 'GET_CLASSROOMS_FAILURE',
    RELOAD_REQUEST: 'RELOAD_REQUEST',
    ADD_REQUEST: 'ADD_CLASSROOM_REQUEST',
    ADD_SUCCESS: 'ADD_CLASSROOM_SUCCESS',
    ADD_FAILURE: 'ADD_CLASSROOM_FAILURE',
    JOIN_REQUEST: 'JOIN_CLASSROOM_REQUEST',
    JOIN_SUCCESS: 'JOIN_CLASSROOM_SUCCESS',
    JOIN_FAILURE: 'JOIN_CLASSROOM_FAILURE',
};

export const authActions = {
    LOGIN_REFRESH: 'LOGIN_REFRESH',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    SOCIAL_LOGIN_REQUEST: 'SOCIAL_LOGIN_REQUEST'
}

export const detailAction = {
    GET_PARTICIPANT_REQUEST: 'GET_PARTICIPANT_REQUEST',
    GET_PARTICIPANT_SUCCESS: 'GET_PARTICIPANT_SUCCESS',
    GET_PARTICIPANT_FAIL: 'GET_PARTICIPANT_FAIL',
    RELOAD_PARTICIPANT_REQUEST: 'RELOAD_PARTICIPANT_REQUEST',
    GET_DETAIL_REQUEST: 'GET_DETAIL_REQUEST',
    GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCESS',
    GET_DETAIL_FAIL: 'GET_DETAIL_FAIL',
    SEND_INVITATION_REQUEST: 'SEND_INVITATION_REQUEST',
    REMOVE_PARTICIPANT_REQUEST:'REMOVE_PARTICIPANT_REQUEST',
    REMOVE_PARTICIPANT_SUCCESS:'REMOVE_PARTICIPANT_SUCCESS',
    REMOVE_PARTICIPANT_FAIL:'REMOVE_PARTICIPANT_FAIL',
    HIDE_PARTICIPANT_REQUEST:'HIDE_PARTICIPANT_REQUEST',
    HIDE_PARTICIPANT_SUCCESS:'HIDE_PARTICIPANT_SUCCESS',
    HIDE_PARTICIPANT_FAIL:'HIDE_PARTICIPANT_FAIL',
    RESTART_DETAIL_REQUEST: 'RESTART_DETAIL_REQUEST'
}

export const assignmentAction = {
    GET_ASSIGNMENTS_REQUEST: 'GET_ASSIGNMENTS_REQUEST',
    GET_ASSIGNMENTS_SUCCESS: 'GET_ASSIGNMENTS_SUCCESS',
    GET_ASSIGNMENTS_FAIL: 'GET_ASSIGNMENTS_FAIL',
    RELOAD_ASSIGNMENTS_REQUEST: 'RELOAD_ASSIGNMENTS_REQUEST',
    UPDATE_POSITION_REQUEST: 'UPDATE_POSITION_REQUEST',
    UPDATE_POSITION_SUCCESS: 'UPDATE_POSITION_SUCCESS',
    UPDATE_POSITION_FAIL: 'UPDATE_POSITION_FAIL',
    ADD_ASSIGNMENT_REQUEST: 'ADD_ASSIGNMENT_REQUEST',
    ADD_ASSIGNMENT_SUCCESS: 'ADD_ASSIGNMENT_SUCCESS',
    ADD_ASSIGNMENT_FAIL: 'ADD_ASSIGNMENT_FAIL',
    REMOVE_ASSIGNMENT_REQUEST: 'REMOVE_ASSIGNMENT_REQUEST',
    REMOVE_ASSIGNMENT_SUCCESS: 'REMOVE_ASSIGNMENT_SUCCESS',
    REMOVE_ASSIGNMENT_FAIL: 'REMOVE_ASSIGNMENT_FAIL',
    UPDATE_ASSIGNMENT_REQUEST: 'UPDATE_ASSIGNMENT_REQUEST',
    UPDATE_ASSIGNMENT_SUCCESS: 'UPDATE_ASSIGNMENT_SUCCESS',
    UPDATE_ASSIGNMENT_FAIL: 'UPDATE_ASSIGNMENT_FAIL',
    GET_STUDENT_INFO_REQUEST:'GET_STUDENT_INFO_REQUEST',
    GET_STUDENT_INFO_SUCCESS:'GET_STUDENT_INFO_SUCCESS',
    GET_STUDENT_INFO_FAIL:'GET_STUDENT_INFO_FAIL',
    RELOAD_STUDENT_INFO_REQUEST:'RELOAD_STUDENT_INFO_REQUEST',
    IMPORT_STUDENT_INFO_REQUEST:'IMPORT_STUDENT_INFO_REQUEST',
    IMPORT_STUDENT_INFO_SUCCESS:'IMPORT_STUDENT_INFO_SUCCESS',
    IMPORT_STUDENT_INFO_FAIL:'IMPORT_STUDENT_INFO_FAIL',
    EXPORT_TEMPLATE_REQUEST:'EXPORT_TEMPLATE_REQUEST',
    ADD_SUBMISSION_REQUEST:'ADD_SUBMISSION_REQUEST',
    ADD_SUBMISSION_SUCCESS:'ADD_SUBMISSION_SUCCESS',
    ADD_SUBMISSION_FAIL:'ADD_SUBMISSION_FAIL',
    IMPORT_SUBMISSION_REQUEST:'IMPORT_SUBMISSION_REQUEST',
    IMPORT_SUBMISSION_SUCCESS:'IMPORT_SUBMISSION_SUCCESS',
    IMPORT_SUBMISSION_FAIL:'IMPORT_SUBMISSION_FAIL',
    UPDATE_SUBMISSION_REQUEST:'UPDATE_SUBMISSION_REQUEST',
    UPDATE_SUBMISSION_SUCCESS:'UPDATE_SUBMISSION_SUCCESS',
    UPDATE_SUBMISSION_FAIL:'UPDATE_SUBMISSION_FAIL',
    FINALIZE_ASSIGNMENT_REQUEST:'FINALIZE_ASSIGNMENT_REQUEST',
    FINALIZE_ASSIGNMENT_SUCCESS:'FINALIZE_ASSIGNMENT_SUCCESS',
    FINALIZE_ASSIGNMENT_FAIL:'FINALIZE_ASSIGNMENT_FAIL',
    FINALIZE_ASSIGNMENT_CONFIRM:'FINALIZE_ASSIGNMENT_CONFIRM',
}

export const accountAction = {
    UPDATE_ACCOUNT_REQUEST: 'UPDATE_ACCOUNT_REQUEST',
    UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
    UPDATE_ACCOUNT_FAIL: 'UPDATE_ACCOUNT_FAIL',
    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAIL: 'UPDATE_PASSWORD_FAIL',
    INIT_ACCOUNT_REQUEST: 'INIT_ACCOUNT_REQUEST',
    INIT_ACCOUNT_SUCCESS: 'INIT_ACCOUNT_SUCCESS',
    UPDATE_STUDENTID_REQUEST:'UPDATE_STUDENTID_REQUEST',
    UPDATE_STUDENTID_SUCCESS:'UPDATE_STUDENTID_SUCCESS',
    UPDATE_STUDENTID_FAIL:'UPDATE_STUDENTID_FAIL',
}

export const gradeAction = {
    GET_GRADE_REQUEST:'GET_GRADE_REQUEST',
    GET_GRADE_SUCCESS:'GET_GRADE_SUCCESS',
    GET_GRADE_FAIL:'GET_GRADE_FAIL',
    RELOAD_GRADE_REQUEST:'RELOAD_GRADE_REQUEST',
    GET_GRADE_REVIEW_REQUEST:'GET_GRADE_REVIEW_REQUEST',
    GET_GRADE_REVIEW_SUCCESS:'GET_GRADE_REVIEW_SUCCESS',
    GET_GRADE_REVIEW_FAIL:'GET_GRADE_REVIEW_FAIL',
    RELOAD_GRADE_REVIEW_REQUEST:'RELOAD_GRADE_REVIEW_REQUEST',
    ADD_GRADE_REVIEW_REQUEST:'ADD_GRADE_REVIEW_REQUEST',
    ADD_GRADE_REVIEW_SUCCESS:'ADD_GRADE_REVIEW_SUCCESS',
    ADD_GRADE_REVIEW_FAIL:'ADD_GRADE_REVIEW_FAIL',
    COMMENT_GRADE_REVIEW_REQUEST: 'COMMENT_GRADE_REVIEW_REQUEST',
    COMMENT_GRADE_REVIEW_SUCCESS:'COMMENT_GRADE_REVIEW_SUCCESS',
    COMMENT_GRADE_REVIEW_FAIL:'COMMENT_GRADE_REVIEW_FAIL',
    FINALIZE_GRADE_REVIEW_REQUEST:'FINALIZE_GRADE_REVIEW_REQUEST',
    FINALIZE_GRADE_REVIEW_SUCCESS:'FINALIZE_GRADE_REVIEW_SUCCESS',
    FINALIZE_GRADE_REVIEW_FAIL:'FINALIZE_GRADE_REVIEW_FAIL'
}

export const commonAction = {
    REDIRECT_REQUEST:'REDIRECT_REQUEST',
    REDIRECT_SUCCESS: 'REDIRECT_SUCCESS'
}