export const classroomActions = {
    GETALL_REQUEST: 'GET_CLASSROOMS_REQUEST',
    GETALL_SUCCESS: 'GET_CLASSROOMS_SUCCESS',
    GETALL_FAILURE: 'GET_CLASSROOMS_FAILURE',
    ADD_REQUEST: 'ADD_CLASSROOMS_REQUEST',
    ADD_SUCCESS: 'ADD_CLASSROOMS_SUCCESS',
    ADD_FAILURE: 'ADD_CLASSROOMS_FAILURE'
};

export const authActions = {
    LOGIN_REFRESH: 'LOGIN_REFRESH',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL'
}